ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

ROTOR_CONFIGURATIONS = [
    'JVIUBHTCDYAKEQZPOSGXNRMWFL',
    'LEYJVCNIXWPBQMDRTAKZGFUHOS',
    'BDFHJLCPRTXVZNYEIWGAKMUSQO',
    'EKMFLGDQVZNTOWYHXUSPAIBRCJ',
    'FKQHTLXOCBJSPDZRAMEWNIUYGV',
    'DMTWSILRUYQNKFEJCAZBPGXOHV',
    'ESOVPZJAYQUIRHXLNFTGKDCMWB',
    'ZOUESYDKFWPCIQXHMVBLGNJRAT',
    'JPGVOUMFYQBENHZRDKASXLICTW',
    'FSOKANUERHMBTIYCWLQPZXVGJD',
    'EHRVXGAOBQUSIMZFLYNWKTPDJC',
    'QYHOGNECVPUZTFDJAXWMKISRBL',
    'NZJHGRCXMYSWBOUFAIVLPEKQDT',
    'AJDKSIRUXBLHWTMCQGZNPYFVOE',
    'UQNTLSZFMREHDPXKIBVYGJCWOA',
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    'NTZPSFBOKMWRCJDIVLAEYUXHGQ',
    'VZBRGITYUPSDNHLXAWMJQOFECK',
    'HQZGPJTMOBLNCIFDYAWVEUSRKX',
    'IMETCGFRAYSQBZXWLHKDVUPOJN',
    'PEZUOHXSCVFMTBGLRINQJWAYDK',
    'QWERTZUIOASDFGHJKPYXCVBNML',
    'JGDQOXUSCAMIFRVTPNEWKBLZYH'
]

REFLECTOR_CONFIGURATIONS = [
    'EJMZALYXVBWFCRQUONTSPIKHGD',
    'YRUHQSLDPXNGOKMIEBFZCWVJAT',
    'FVPJIAOYEDRZXWGCTKUQSBNMHL',
    'ENKQAUYWJICOPBLMDXZVFTHRGS',
    'RDOBJNTKVEHMLFCWZAXGYIPSUQ',
]
